# Generated by Django 5.0.3 on 2024-03-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_remove_creation_counted_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='published_date',
        ),
    ]
