# Generated by Django 5.0.3 on 2024-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_rename_userid_exhibition_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateTimeField(verbose_name='Y/M/D'),
        ),
    ]
