# Generated by Django 5.0.3 on 2024-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_teaching_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
