# Generated by Django 5.0.3 on 2024-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_alter_teaching_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
